### ISSUE TITLE
Port forwarding requires a Professional license

### ISSUE THREAD

**Issue by pdonovan** [VMwareFusion/nautilus#20]
I have a standard license of Fusion, not a Professional license. None of the guides mention that port forwarding of containers isn't supported in the standard version:
```
% vctl run --name=redis -t -d -p 6379:6370 -p 6380:6380 redis
ERROR failed to run command:/Applications/VMware Fusion.app/Contents/Public/vmrun -T fusion listHostNetworks, err:exit status 255  module=libcrx package=vmrun
ERROR failed to set up port forwardings: failed to get container network: error code:exit status 255, message:Error: There is no valid Professional license to run this command
, stopping container... 
INFO container redis has been stopped             
ERROR failed when running container redis: unable to set up port forwardings
```

Is this a bug, or a documentation error? I specifically chose to renew my Fusion license because of    vctl and now find I can't use it.

**Comment by yeahdongcn** [comment]
Please ref to https://docs.vmware.com/en/VMware-Fusion/11/com.vmware.fusion.using.doc/GUID-78E7339F-7294-4F3E-9AD0-1E14C201FA40.html

> However, the --publish option is only available with Fusion Pro.

**Comment by pdonovan** [comment]
Thanks, I didn’t find that page. 

Is there any chance of that limitation being reconsidered? I was hoping to avoid having to run both Fusion (for Windows) and Docker at the same time.

**Comment by mikeroySoft** [comment]
It's something we're investigating.
FWIW, users don't actually need to forward ports if you're just working locally.
The way vctl works is that the container appliance vm (we call it the crx-vm) gets an IP address from it's attached VMnet.

So you grab the IP of the crx-vm with `vctl ps` and just hit the ports directly.

The publish feature would essentially create a NAT rule on the VMNet, which would allow you to expose container services from the host to the outside world.
