### ISSUE TITLE
Location of vctl?

### ISSUE THREAD

**Issue by stevesloka** [VMwareFusion/nautilus#3]
I installed the preview of Fusion and can't find the binary `vctl` which is mentioned in the quick start. I'm running oh-my-zsh, so I might need to update my paths manually. 

Is there a default place this gets placed on the system?

**Comment by mikeroySoft** [comment]
It should have been added to your Path with vmrun and the other cli tools as a part of the installation. It’s lives in /Applications/VMware Fusion Tech Preview/Contents/Public/

**Comment by stevesloka** [comment]
Found it! 🎉
