### ISSUE TITLE
Issues with closed ports inside containers

### ISSUE THREAD

**Issue by matthewmorek** [VMwareFusion/nautilus#36]
I am trying to understand how does port forwarding work with `vctl` as none of my apps within containers report having their ports open to the outside world via NAT.

### Steps to reproduce
1. `vctl pull linuxserver/transmission` (https://hub.docker.com/r/linuxserver/transmission)
2. Create and run a Transmission container:
    ```
    vctl run -d \
    --name=transmission \
    -e PUID=1000 \
    -e PGID=1000 \
    -e TZ=Europe/London \
    -p 9091:9091 \
    -p 51413:51413 \
    -p 51413:51413/udp \
    -v <path to data>:/config \
    -v <path to downloads>:/downloads \
    -v <path to watch folder>:/watch \
    --restart unless-stopped \
    linuxserver/transmission
    ```
3. Access Transmission's Web UI by going to `localhost:9091/transmission/web/` in your browser.
4. Click on a 🔧  icon to access `Settings`
5. Click on the `Network` tab, wait a few seconds
6. Check status of a default port

### Expected result
The following ports should be open:
- `51413/tcp`
- `51413/udp`

### Actual result
The port is closed

### Additional info
- The same ports (more than one) have been tested on the host using another instance of Transmission, and the port appears open, so the NAT is definitely working.
- There is no "double NAT" issue on the tested network
- Port forwarding isn't active on the router

**Comment by matthewmorek** [comment]
I just realised that vm containers are behind a different network, which makes it impossible for NAT to work, and this a manual port forwarding needs to be setup on the router to achieve desired outcome.

Closing this issue, but feel free to provide a bit more insight (or point me to the right page) into how networking inside `vctl` in general.

**Comment by mikeroySoft** [comment]
So the short answer is 'it depends on how you're accessing it'.
For instance, running the container creates a new container host ('CRX VM' appliance), and that VM gets an IP on the vmnet that it is connected to. In this case, the VM gets it's IP from the vmnet and port forwarding is not required when accessing it from the local host. (i.e. you just go to "172.x.x.x:51413" or whatever the IP is).

When you want to share the service outside of the computer it's running on, that's where the -p flag applies.
What it does in this context is create a NAT rule on the vmnet directly. So you can access it from outside the local host by hitting the IP of the physical device and the port you're exposing. That gets forwarded to the "172.x.x.x" or whatever IP the VM gets.

That said, the port forwarding feature of the vmnet is historically a Pro only feature.
So while Fusion and Workstation Player can deploy a container and access it from the local host, it can't be shared in the same way (so you'd need to create some rule at your router to do the port forwarding)
